#!/bin/sh

DATA=/local/data
OVERLAY=/local/overlay

mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sysfs /sys -o nosuid,noexec,nodev
mount -t tmpfs tmpfs /tmp -o nosuid,nodev,noatime,size=2M
mount -t tmpfs tmpfs $OVERLAY -o nosuid,nodev,noatime,size=5M

if ! fdisk -l | grep -q mmcblk0p2; then
  echo -e "n\np\n2\n\n+32M\nw\n" | fdisk /dev/mmcblk0
fi

if ! mount -t ext4 /dev/mmcblk0p2 $DATA; then
  mkfs.ext4 /dev/mmcblk0p2
  mount -t ext4 /dev/mmcblk0p2 $DATA
fi

for d in etc etc.work var var.work; do
  mkdir -p $OVERLAY/$d
done
mount -t overlay -o lowerdir=/etc,upperdir=$OVERLAY/etc,workdir=$OVERLAY/etc.work overlay /etc
mount -t overlay -o lowerdir=/var,upperdir=$OVERLAY/var,workdir=$OVERLAY/var.work overlay /var
mount -t tmpfs tmpfs /var/log -o nosuid,nodev,noatime,size=10M

if [ -e $DATA/etc/sysconfig ]; then
  cp $DATA/etc/sysconfig /etc/sysconfig
fi

HOSTNAME="$(cat /etc/sysconfig | grep SYS_HOSTNAME | cut -d= -f2 | xargs)"
if [ "$HOSTNAME" ]; then
  hostname "$HOSTNAME"
fi
